frontend/models/Gift.php
<?php

namespace frontend\models;

class Gift extends BaseGift
{
	const NAME = 'Подарок';
	const POST_SYSTEM = 'giftPostSystem';

	public function rules()
	{
		return [
			[['name', 'amount'], 'required'],
			[['name', 'description', 'amount'], 'safe']
		];
	}

	public function getStore()
	{
		return $this->hasOne(Store::class, ['id' => 'store_id']);
	}

	public function getUserGift()
	{
		return $this->hasOne(UserGift::class, ['gift_id' => 'id']);
	}
}

frontend/controllers/GiftController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;


class GiftController extends Controller
{

	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::class,
				'only' => ['index','convert', 'refund', 'cabinet'],
				'rules' => [
					[
						'actions' => ['index', 'convert', 'refund', 'cabinet'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
			'verbs' => [
				'class' => VerbFilter::class,
				'actions' => [
					'index' => ['GET'],
					'cabinet' => ['GET'],
				],
			],
		];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class' => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	public function actionIndex()
	{
		try {
			$gift = Yii::$app->gift->create();
			Yii::$app->store->changeCapacity($gift);
			try {
				Yii::$app->gift->add($gift);
			} catch (\Exception $e) {
				Yii::$app->store->recoveryCapacity($gift);
				Yii::$app->gift->remove($gift);
				Yii::$app->session->setFlash('Error', $e->getMessage());
				return $this->redirect('/gift/cabinet');
			}
		} catch (\Exception $e) {
			$message = YII_ENV_PROD ? 'Get gift error' : 'Error' . $e->getMessage();
			Yii::$app->session->setFlash('Error', $message);
			return $this->redirect('/');
		}
		return $this->render('index', [
			'gift' => $gift,
		]);
	}

	public function actionRefund(int $id)
	{
		try {
			$gift = Yii::$app->gift->oneById($id);
			if (Yii::$app->gift->remove($gift)) {
				Yii::$app->store->recoveryCapacity($gift);
			};
			Yii::$app->session->setFlash('Success', 'Вернули!');
			return $this->redirect('/gift/cabinet');
		} catch (\Exception $e) {
			$message = YII_ENV_PROD ? 'Refund error' : 'Error' . $e->getMessage();
			Yii::$app->session->setFlash('Error', $message);
			return $this->redirect('/');
		}
	}

	public function actionConvert(int $id, int $type)
	{
		try {
			$gift = Yii::$app->gift->oneById($id);
			Yii::$app->converter->convert($gift, $type);
			Yii::$app->session->setFlash('Success', 'Конвертнули!');
			return $this->redirect('/gift/cabinet');
		} catch (\Exception $e) {
			$message = YII_ENV_PROD ? 'Convert error' : 'Error: ' . $e->getMessage();
			Yii::$app->session->setFlash('Error', $message);
			return $this->redirect('/gift/cabinet');
		}
	}

	public function actionCabinet()
	{
		try {
			$storeDataProvider = Yii::$app->store->all(['>', 'amount', 0]);
			$giftDataProvider = Yii::$app->gift->all(['user_id' => Yii::$app->user->id]);
		} catch (\Exception $e) {
			$message = YII_ENV_PROD ? 'Get gift error' : 'Error' . $e->getMessage();
			Yii::$app->session->setFlash('Error', $message);
			return $this->redirect('/');
		}
		return $this->render('cabinet', [
			'giftDataProvider' => $giftDataProvider,
			'storeDataProvider' => $storeDataProvider
		]);
	}

}

frontend/views/gift/cabinet.php
<?php

/**
 * @var $this yii\web\View
 * @var BaseGift $gift
 * @var ActiveDataProvider $giftDataProvider
 * @var ActiveDataProvider $storeDataProvider
 */

$this->title = 'My Yii Application';

use frontend\enums\GiftTypeEnum;
use frontend\helpers\GiftStatusHelper;
use frontend\helpers\GiftTypeHelper;
use frontend\models\BaseGift;
use yii\bootstrap\Html;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\helpers\Url;

?>
<div class="site-index">
    <div class="jumbotron">
		<?=
		GridView::widget([
			'dataProvider' => $storeDataProvider,
			'columns' => [
				'amount',
				[
					'attribute' => 'type',
					'format' => 'raw',
					'value' => function ($model) {
						return GiftTypeHelper::typeTranslateToString($model->type);
					},
				],
			],
		]) ?>    </div>
    <div class="jumbotron">
		<?=
		GridView::widget([
			'dataProvider' => $giftDataProvider,
			'columns' => [
				[
					'attribute' => 'id',
					'format' => 'raw',
					'value' => function ($model) {
						return $model->gift->id;
					},
				],
				[
					'attribute' => 'type',
					'format' => 'raw',
					'value' => function ($model) {
						return GiftTypeHelper::typeTranslateToString($model->gift->store->type);
					},
				],
				[
					'attribute' => 'amount',
					'format' => 'raw',
					'value' => function ($model) {
						return $model->gift->amount;
					},
				],
				[
					'attribute' => 'amount',
					'format' => 'raw',
					'value' => function ($model) {
						return $model->gift->amount;
					},
				],
				[
					'attribute' => 'status',
					'format' => 'raw',
					'value' => function ($model) {
						return GiftStatusHelper::statusTranslateToString($model->gift->userGift->status);
					},
				],
				[
					'class' => 'yii\grid\ActionColumn',
					'template' => '{convert}',
					'buttons' => [
						'convert' => function ($url, $model, $key) {
							return Html::a('Convert', Url::to(['gift/convert', 'id' => $model->gift->id, 'type' => $model->gift->store->type == GiftTypeEnum::CASH ?? GiftTypeEnum::BONUS_POINTS]));
						},
					]
				],

			],
		]) ?>
    </div>

</div>
</div>

frontend/views/gift/error.php
<?php

/* @var $this yii\web\View */
/** @var BaseGift $gift */
$this->title = 'My Yii Application';

use frontend\models\BaseGift; ?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Ваш подарок застрял!!!!</h1>

        <p class="lead">А еще он <?= $errorMessage ?> </p>

    </div>

</div>
</div>

frontend/views/gift/index.php
<?php

/* @var $this yii\web\View */
/** @var BaseGift $gift */
$this->title = 'My Yii Application';

use frontend\models\BaseGift; ?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Ваш приз это <?= $gift->name ?>!</h1>

        <p class="lead">You Won <?= $gift->amount ?> of them </p>

        <p><a class="btn btn-lg btn-success" href="/gift/refund?id=<?= $gift->id ?>">Вернуть! Не нравится!</a></p>
    </div>

</div>
</div>